-- Las tareas diarias ahora viven en la migración 0006_cron.sql y leen la URL
-- y el CRON_SECRET del Vault. Para un proyecto nuevo, después de `db push`:
--
--   supabase secrets set CRON_SECRET=<secreto>
--   select vault.create_secret('https://<ref>.supabase.co', 'moneytrack_project_url');
--   select vault.create_secret('<secreto>', 'moneytrack_cron_secret');
--
-- Revisar ejecuciones:  select * from cron.job_run_details order by start_time desc limit 10;
-- Probar a mano:        select public.call_moneytrack_function('sync-rates');
